services:
  integration-testing:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mlops-project
    ports:
      - 9696:9696
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    