FROM python:3.9.7-slim

RUN pip install -U pip
RUN pip install pipenv

WORKDIR /app
COPY ["/integration_files/Pipfile", "/integration_files/Pipfile.lock", "./"]
RUN pipenv install --system --deploy

COPY ["/integration_files/FE_categorical_columns.py", "/integration_files/ordinal_columns_encoding.py", "/integration_files/predict.py", "./"]

RUN mkdir model
COPY ["/integration_files/model.pkl", "/integration_files/standard_scaler.pkl", "./model/"]

EXPOSE 9696
CMD ["gunicorn", "--timeout", "1000"] 
ENTRYPOINT [ "gunicorn", "--bind=0.0.0.0:9696", "predict:app" ]